-- 코드를 입력하세요
SELECT ins.ANIMAL_ID, ins.ANIMAL_TYPE, ins.NAME
FROM ANIMAL_INS ins, ANIMAL_OUTS outs
WHERE ins.ANIMAL_ID = outs.ANIMAL_ID
AND ins.SEX_UPON_INTAKE LIKE '%Intact%' 
AND (outs.SEX_UPON_OUTCOME LIKE '%Spayed%' OR outs.SEX_UPON_OUTCOME LIKE '%Neutered%');