-- 코드를 작성해주세요
SELECT SUM(grade.SCORE) AS SCORE, emp.EMP_NO, emp.EMP_NAME, emp.POSITION, emp.EMAIL
FROM HR_EMPLOYEES emp
JOIN HR_GRADE grade
ON emp.EMP_NO = grade.EMP_NO
WHERE grade.YEAR = 2022
GROUP BY grade.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;