-- 코드를 작성해주세요
SELECT emp.DEPT_ID, dept.DEPT_NAME_EN, ROUND(AVG(emp.SAL)) AS AVG_SAL
FROM HR_EMPLOYEES emp, HR_DEPARTMENT dept
WHERE emp.DEPT_ID = dept.DEPT_ID
GROUP BY emp.DEPT_ID
ORDER BY AVG_SAL DESC;